### PR TITLE
Make the application usable

### PR DESCRIPTION
**Pull request by janus2**
- The application compiles again (Makefile, headers fix).
- Introduce layout in the option window.
- Remove Load and Save for height/width they look ugly and confusing (Are useful?)
- Change the background from black to the same pattern of Filer.
TODO
- Use BAboutWindow for About window
- Modify cord window and use a better widget to show the window (checkbox?)
- Insert message drag and drop with suggestion in main window
- Suggestions are welcome

### CODE REVIEW

**Comment by humdingerb** [comment]
Nice work!

* Would be nice if all the actions were done "live", i.e. no "Apply" button needed. This should be done in separate (multiple) thread(s) so it's not blocking the GUI for large images.

* "Smooth scaling" should be a checkmark option. ShowImage shows that with the right algorithm and today's hardware this shouldn't be a problem to do live today.

* Resizing without keeping the aspect ratio should limit the horizontal/vertical window size. Right now the window shows a white background, which isn't that nice.

* Maybe add a bit of padding round the buttons, to uncramp the layout a bit.

* Add a pop-up menu with standard sizes, see WonderBrush's "New canvas" window.

* Change "As" to "Format". Add ":" to all labels.

* I don't like the floating Options window too much. IMO it should always be visible and not hide when some other app has focus. It should also be resizable.

* Use an rdef and add supported filetypes to get TAresizer into Tracker's "Open" menu:
```
resource file_types message {
	"types" = "image",
	"types" = "application/x-vnd.haiku-icon"
};
```

The list got longer and longer... :)
Want me to file issues for each?

**Comment by janus2** [comment]
You can wait, I'll try to fix the simple issues first... after that we can open a ticket for the remaining problems.

**Comment by humdingerb** [comment]
With regard to the used image format, it'd be even better to default to the dropped image's format, I think.

**Comment by janus2** [comment]
If you choose a different format and then drop an image or if you drop different images with different format... I choose one format because the discoverability of how to save an image is not very good (a suggestion in the window will help) but if you do not select a format you cannot drag the image making the process very annoying.

**Comment by janus2** [comment]
TAResizer
===
- [X] Use BAboutWindow for About window
- [X] Modify cord window and use a better widget to show the window (checkbox?)
- [ ] Insert message drag and drop with suggestion in main window
- [X] Sensible default for the format field
- [X] Resizing without keeping the aspect ratio should limit the horizontal/vertical window size. Right now the window shows a white background, which isn't that nice.
- [X] Maybe add a bit of padding round the buttons, to uncramp the layout a bit.
- [X] Change "As" to "Format". Add ":" to all labels.
- [X] I don't like the floating Options window too much. IMO it should
  always be visible and not hide when some other app has focus.
- [X] Use an rdef and add supported filetypes to get TAresizer into Tracker's "Open" menu:
```
resource file_types message {
	"types" = "image",
	"types" = "application/x-vnd.haiku-icon"
};
```

Question that need some considerations
===
-  Would be nice if all the actions were done "live", i.e. no "Apply" button needed. This should be done in separate (multiple) thread(s) so it's not blocking the GUI for large images.

See my previous comment 

- Add a pop-up menu with standard sizes, see WonderBrush's "New canvas" window.

I think this is useful for a new canvas. An image have already an aspect ratio that a standard size cannot accomodate.

- "Smooth scaling" should be a checkmark option. ShowImage shows that with the right algorithm and today's hardware this shouldn't be a problem to do live today.

"Smooth scaling" works only with shrunk images when the haiku bilinear filter works with enlarged images.

- It should also be resizable (Option window).

Why? The widgets are almost all buttons not need to resize the window.

**Comment by humdingerb** [comment]
After some thought, I agree with most of your assessments.

WRT to "Smooth scaling", it'd be best to transparently use the appropriate algorithm for scaling down/up, no?

The resizable "Options" window would probably only be of interest for the file name. BTW, "Filename:" would be better as label IMO.

**Comment by janus2** [comment]
> WRT to "Smooth scaling", it'd be best to transparently use the appropriate algorithm for scaling down/up, no?

I thought about that.
 "Smooth scaling" now works as a filter. The image will look degraded if enlarged again.
I will try to apply the filter live and see if it is not too expensive.

**Pull request merged**
