### PR TITLE
Add file open dialog

### LINKED ISSUE #12: Click empty image window for file open dialog

### LINKED ISSUE #14: Convert ReadMe to Markdown and add Screenshot

### PR DESCRIPTION
**Pull request by dospuntos**
This PR is related to issue #12 . Clicking the empty dropzone will show a file open dialog. The dialog will only display folders and image files. The image filter `RefFilters` was borrowed from ArtPaint...

Fixes #12
Fixes #14

### CODE REVIEW

**Comment by humdingerb** [comment]
If you add as last line "Fixes #12" the issue will get automatically closed when this is merged.

**Comment by dospuntos** [comment]
> If you add as last line "Fixes #12" the issue will get automatically closed when this is merged.

Oh, I didn't know that. Nice.

**Comment by dospuntos** [comment]
@humdingerb just checking to see if you've had a chance to test this?

**Review by humdingerb — COMMENTED** [review]
Thanks for reminding me. Sorry, I forgot about it...

I even had a review of very minor things that I apparently haven't submitted back then and that was "Pending"...

**Comment by dospuntos** [comment]
Thanks, no worries, I see you've been very busy helping with Genio lately 👍 
I've applied those changes. Can this app be added to Polyglot at some point, now that it is localized?

**Comment by humdingerb** [comment]
> Thanks, no worries, I see you've been very busy helping with Genio lately
Well... code contributions are minimal, but I test and updated the user guide. :)

I'll add TAResizer to Polyglot momentarily. Feel free to post to https://discuss.haiku-os.org/t/translations-needed-for-upcoming-3rd-party-app-release/11997 when I'm done.

**Comment by humdingerb** [comment]
I had a few minor changes. Have a look at https://i18n.kacperkasper.pl/projects/52 and finish the few "fuzzy" blocks. A good thing, too, that way you should get the auto-credit at Polyglot for the Norwegian translation. :)

**Pull request merged**
